In [ ]:
print("Day-1")

Day-1


In [ ]:
print("himalay")

himalay


In [ ]:
#list introduction

In [ ]:
a=["hi","hello","world"]

In [ ]:
print(a)

['hi', 'hello', 'world']


In [ ]:
a = [10,20,30]
print(a)

[10, 20, 30]


In [ ]:
print(type(a))

<class 'list'>


In [ ]:
# list is hetrogeneous
b=[10,1,1.22,'NTT']
print(b)
print(type(b))

[10, 1, 1.22, 'NTT']
<class 'list'>


In [ ]:
# length of  the list
print(len(b))

4


In [ ]:
# List creation using constructor --- list()

l = list((10,20,3.33,'ntt'))
print(l)
print(type(l))


[10, 20, 3.33, 'ntt']
<class 'list'>


In [ ]:
# access elements in list
print(l[0])

10


In [ ]:
# for loop in list
for i in l:
  print(i)

10
20
3.33
ntt


In [ ]:
print(l[3].upper())

NTT


In [ ]:
print(l[-1])

ntt


In [ ]:
print(l[-3])

20


In [ ]:
# Range of index
a=[10,20,30,40,50,60,70]
b=a[1:]
c=a[1:6]
#negitive will be some what different
d=a[-3:-1]
print(a)
print(b)
print(c)
print(d)

[10, 20, 30, 40, 50, 60, 70]
[20, 30, 40, 50, 60, 70]
[20, 30, 40, 50, 60]
[50, 60]


In [ ]:
# Index error means range of index is outbound
a=[10,20,30,40,50,60,70]
print(a[10])

IndexError: list index out of range

In [ ]:
a=[10, 20, 30, 40, 50, 60, 70]
#[start:end:step]
print(a[0:7:1])
print(a[0:7:2])
print(a[-7::1])
print(a[-7:-1:1])

[10, 20, 30, 40, 50, 60, 70]
[10, 30, 50, 70]
[10, 20, 30, 40, 50, 60, 70]
[10, 20, 30, 40, 50, 60]


In [ ]:
a=[10,20,30,40,50]
a[1]=500
a[1:3]=['NTT','Hi']
print(a)
a[1:3]=['NTT','Hi',"hy",89,7.9,10]
print(a)

[10, 'NTT', 'Hi', 40, 50]
[10, 'NTT', 'Hi', 'hy', 89, 7.9, 10, 40, 50]


In [ ]:
# append will add the elemen in last
a.append(1000)
print(a)

[10, 'NTT', 'Hi', 'hy', 89, 7.9, 10, 40, 50, 1000]


In [ ]:
# insert will add the element in a particular index
# insert(index,element)
a.insert(1,55)
print(a)

[10, 55, 'NTT', 'Hi', 'hy', 89, 7.9, 10, 40, 50, 1000]


In [ ]:
l=[99,999,99999]
l2=[40,60,100]
l2.extend(l)
print(l2)

[40, 60, 100, 99, 999, 99999]


In [ ]:
# to remove elements
l2.remove(99)
print(l2)

[40, 60, 100, 999, 99999]


In [ ]:
# to remove elements which are not there in list
l2.remove(100000)
print(l2)

ValueError: list.remove(x): x not in list

In [ ]:
# pop function will help to remove the element at aparticular index
# pop(index)
l2.pop(0)
print(l2)

[100, 999, 99999]


In [ ]:
# to delete a list entirly
del l2
print(l2)

NameError: name 'l2' is not defined

In [ ]:
a=[1,2,3,4]
del a[0]
print(a)

[2, 3, 4]


In [ ]:
#to clear all elements in list
a=[1,2,3,4]
a.clear()
print(a)

[]


In [ ]:
# For loop for list
a=[1,2,3,4,5,6,7]
for i in a:
  print(i)

1
2
3
4
5
6
7


In [ ]:
# While loop
a=1
while a<10:
  print(a)
  a=a+1

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(1,10,1):
  print(i)

1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(0,11,2):
  print(i)

0
2
4
6
8
10


In [1]:
# Numpy Practice
import numpy as np
a=[1,2,3]
b=np.array(a)
print(b)

[1 2 3]


In [3]:
print(b[0])
print(b[1])
print(b[2])

1
2
3


In [5]:
a=[1,2,3,4]
b=np.array(a).reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [14]:
a=[1,2,3,4,5,6,7,8,9]
b=np.array(a).reshape(3,3)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
a=[1,2,3,4,5,6,7,8,9,11,22,33,44,55,66,77,88,99]
b=np.array(a).reshape(3,2,3)
print(b)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]

 [[44 55 66]
  [77 88 99]]]


In [18]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [19]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [24]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[11,22]]])
print(a)
a.shape

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9  0]
  [11 22]]]


(3, 2, 2)

ValueError: cannot reshape array of size 18 into shape (2,2,2)

In [35]:
a=np.zeros([5,2,3])
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [36]:
a.fill(1)

In [37]:
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [41]:
# it will create random integers in the given dimensions
b=np.random.rand(5,2,3)
print(b)

[[[0.03758129 0.51263563 0.34105825]
  [0.98685192 0.52051981 0.51477896]]

 [[0.1598847  0.69436779 0.45334746]
  [0.03541159 0.58519958 0.25795806]]

 [[0.86354494 0.95576942 0.67908283]
  [0.1011851  0.97572899 0.71379396]]

 [[0.3748356  0.76666802 0.51936617]
  [0.98759368 0.77453752 0.71681576]]

 [[0.47601344 0.22371711 0.5841614 ]
  [0.62496342 0.56612888 0.57985973]]]


In [48]:
c=np.ones(7)
print(c)
d=np.ones([2,3])
print(d)

[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [57]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)[source]
# n = rows, M=coloums,k= 0 (main diagonal) 1 (upper diagnal),-1 (lower diagnal)
e=np.eye(3,3,1)
print(e)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [63]:
# arange(start,stop,step)
a=np.arange(0,12,2)
print(a)
a.reshape(3,2,1)

[ 0  2  4  6  8 10]


array([[[ 0],
        [ 2]],

       [[ 4],
        [ 6]],

       [[ 8],
        [10]]])

In [66]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)
# returns evenly spaced numbers
a=np.linspace(0,10,5,endpoint=True)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [68]:
# numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)[source]
a=np.logspace(0,10,3,base=2)
print(a)

[1.000e+00 3.200e+01 1.024e+03]
