In [1]:
import numpy as np

In [2]:
a=[1,2,3,4]
b=np.array(a)
print(b)

[1 2 3 4]


In [3]:
b.reshape(4,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [4]:
#n dimensional array are only possible in the python

In [10]:
a=np.random.rand(5,2,3)
print(a)

[[[0.5847578  0.53190934 0.40764432]
  [0.18208199 0.67110628 0.64467907]]

 [[0.05134281 0.74191576 0.00686809]
  [0.56063393 0.69779032 0.75863148]]

 [[0.85838317 0.05700649 0.03591641]
  [0.45147106 0.26856215 0.11285468]]

 [[0.24507733 0.85630647 0.6243021 ]
  [0.63276949 0.57688254 0.1607648 ]]

 [[0.65339083 0.91556483 0.24962673]
  [0.62061375 0.61597445 0.37460333]]]


In [11]:
np.ones([5,3,3])

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
np.zeros([5,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
np.eye(3,3,0,order='C')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr1 = np.array(100)
arr2= np.array([1,2,3,4,5])
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr1)
print(arr4.ndim)

100
3


In [25]:
arr5 = np.array([1,2,3,4,5],ndmin=5)
print(arr5)
# By this output the 5th dim has 5 elements and remaining has one element only

[[[[[1 2 3 4 5]]]]]


In [26]:
arr5 = np.array([1,2,3,4,5],ndmin=5)
print(arr5)

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-26-c023f1387bbd>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  arr5 = np.array([1,2,3,4,5][1,2,3],ndmin=5)


TypeError: list indices must be integers or slices, not tuple

In [29]:
a=[1,2,3,4,5,6,7,8,9,0]
a=np.array(a)
b=a.reshape(5,1,2)
print(b,b.ndim)

[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]

 [[9 0]]] 3


In [30]:
# How to access the array
print(b[0][0][1])

2


In [33]:
print(b[0][0][::1])

[1 2]


In [34]:
print(b[0][0][::2])

[1]


In [35]:
print(b[0][0][::-1])

[2 1]


In [38]:
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1[0][:2])

[1 2]


In [39]:
print(ar1[0,1])

2


In [42]:
print(ar1[0,:2])

[1 2]


In [44]:
ar2 = np.array([1,2,3,4,5])
l=ar2[1:4]
print(l)
print(type(l))

[2 3 4]
<class 'numpy.ndarray'>


In [47]:
ar3 = np.array([1,2,3,4,5,"Ntt"])
print(ar3.dtype)
#u21
# What ever highest datatype that will come in the response

<U21


In [48]:
ar1 = np.array([1,2,3,4,5],dtype = 'int')
print(ar1)

[1 2 3 4 5]


In [50]:
ar1 = np.array([1,2,3,4,5],dtype = 'S')
print(ar1)
print(ar1.dtype)
#i4 = int32
#i8 = int64
#S = string

[b'1' b'2' b'3' b'4' b'5']
|S1


In [51]:
ar1 = np.array([1,2,3,4,5])
na = ar1.astype('i')
# in place of i we can use 'int','bool' also
print(na)
print(na.dtype)

[1 2 3 4 5]
int32


In [52]:
# copy and view
#copy = new a new array
#view = it will not create new array
ar1 = np.array([1,2,3,4,5])
x=ar1.copy()
ar1[0]=42
print(x)
print(ar1)

[1 2 3 4 5]
[42  2  3  4  5]


In [53]:
ar1 = np.array([1,2,3,4,5])
x=ar1.view()
ar1[0]=42
print(x)
print(ar1)

[42  2  3  4  5]
[42  2  3  4  5]


In [55]:
# numpy array shape
# shape tells the dimension of the array
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1.shape)

(2, 3)


In [57]:
ar1 = np.array([[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]],[[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
print(ar1.shape)

(2, 2, 2, 3)


In [59]:
# we can convert a array to into different shape
# reshape()
a=np.array([1,2,3,4])
b=a.reshape(4,1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [64]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
c=a.reshape(2,2,3)
print(b)
print('###############################')
print(c)
for i in c:
  print(i)
  print('0000000000000000')
print(b.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
###############################
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [4 5 6]]
0000000000000000
[[ 7  8  9]
 [10 11 12]]
0000000000000000
(4, 3)


In [65]:
# reshape(2,3,?) That ? can be replaced with -1 so that the system will calculate
# We can use -1 at any position

In [67]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
c=a.reshape(2,2,3)
d=a.reshape(2,-1,2)
print(d)
e = a.reshape(-1) # its a one dimensional array
print(e)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
