In [2]:
print("day-3")

day-3


In [6]:
# tuple

In [7]:
a=(1,2,3)
print(a)
print(a[0])

(1, 2, 3)
1


In [8]:
a[0]=55

TypeError: 'tuple' object does not support item assignment

In [9]:
# in tuple we cannot change anything


In [11]:
a.append(30)
# we can not append also even deleting is also not possible

AttributeError: 'tuple' object has no attribute 'append'

In [12]:
# we can iterate through the tuple


In [15]:
b= tuple((1,2,3,4,'ntt'))
print(b)
print(type(b))

(1, 2, 3, 4, 'ntt')
<class 'tuple'>


In [16]:
c= tuple((1,1,2,3,4,'ntt'))
print(c)

(1, 1, 2, 3, 4, 'ntt')


In [17]:
a=[1,2,3]
b=tuple(a)
print(b)

(1, 2, 3)


In [18]:
a=tuple(9)
print(a)

TypeError: 'int' object is not iterable

In [19]:
a=tuple((10))

TypeError: 'int' object is not iterable

In [20]:
# to add one element

In [21]:
a=tuple((10,))
print(a)

(10,)


In [22]:
a=tuple(('him'))
print(a)

('h', 'i', 'm')


In [25]:
a=tuple(['him'])
print(a)
a=tuple(("him"))
print(a)

('him',)
('h', 'i', 'm')


In [28]:
a=[1,2,3]
b=[22,33,44]
c=tuple(a)
print(c)

(1, 2, 3)


In [33]:
a=(1,2,4,3,5,6,7)
print(a[0])
print(a[-1])
print(a[0:5])
print(a[0:5:2])

1
7
(1, 2, 4, 3, 5)
(1, 4, 5)


In [34]:
if 2 in a:
  print('yes')
else:
  print('no')

yes


In [35]:
# indirect method to add a element in tuple
a=(1,2)
b=list(a)
print(b)
b.append(3)
c=tuple(b)
print(c)

[1, 2]
(1, 2, 3)


In [36]:
a=(1,2,3,4)
for i in a:
  print(i)

1
2
3
4


In [40]:
#  Dictornieries are nothing but naming the index
a={'india':'delhi','russia':'mascow'}
print(a['india'])
print(a)


delhi
{'india': 'delhi', 'russia': 'mascow'}


In [42]:
b=dict(name="jiji",age=21)
print(b)
b['name']


{'name': 'jiji', 'age': 21}


'jiji'

In [44]:
for i in b:
  print(i)
  print(b[i])

name
jiji
age
21


In [45]:
# to fetch all the keys
x=b.keys()
print(x)

dict_keys(['name', 'age'])


In [46]:
# to fetch all the values
x=b.values()
print(x)

dict_values(['jiji', 21])


In [47]:
# to get both ekeys and values
z=b.items()
print(z)

dict_items([('name', 'jiji'), ('age', 21)])


In [48]:
# to change the value
b['name']="him"
print(b)

{'name': 'him', 'age': 21}


In [49]:
# we can use update also
b.update({"name":"king"})
print(b)

{'name': 'king', 'age': 21}


In [51]:
# to add a element
b['school']="bhash"
print(b)

{'name': 'king', 'age': 21, 'school': 'bhash'}


In [52]:
# to delete the element
# .popitem()======> this will delete the last element
# del b ===> it will delete dict
# del b['name'] ===> it will delete te name
b.pop("school")
print(b)

{'name': 'king', 'age': 21}


In [58]:
#################################################
# NUMPY #
# Numerical Python
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
5
(5,)
int64
1


In [61]:
# 2d array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
int64
2


In [63]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[11,22,33],[44,55,66]]])
print(arr3)
print(arr3.size)
print(arr3.shape)
print(arr3.dtype)
print(arr3.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
12
(2, 2, 3)
int64
3
